### ISSUE TITLE
Tensorflow runs under bash for ubuntu for windows

### ISSUE THREAD

**Issue by chm90** [zer0n/deepframeworks#19]
Hi there. Well written, just wanted to add that even though there isn't any official support for tensorflow under windows, I can confirm it does run under the bash for ubuntu for windows beta. Haven't tried GPU though.

**Comment by iev6** [comment]
does the GPU work? I don't think the bash in windows gets access to the GPU memory.

**Comment by marian-margeta** [comment]
Actually tensorflow runs under windows natively at least since version 0.12. I am using it in Win 10 and it works perfectly. It should have also support for GPU with CUDA 8, but I haven't tried it yet. For installing under win with GPU, try following command:
`pip install tensorflow-gpu `

more info:
https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html
